# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"unpack_smpl": "00_core.ipynb",
         "unpack_smplh": "00_core.ipynb",
         "unpack_smplh_from_mano": "00_core.ipynb",
         "canonical_smpl_names": "00_core.ipynb",
         "create_bmlink": "00_core.ipynb",
         "console_unpack": "00_core.ipynb",
         "init_body_model": "00_core.ipynb",
         "sample_betas": "00_core.ipynb",
         "plottable": "00_core.ipynb",
         "SMPLH_JOINT_NAMES": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://gngdb.github.io/gaitplotlib/"

git_url = "https://github.com/gngdb/gaitplotlib/tree/master/"

def custom_doc_links(name): return None
